CREATE TABLE USERS (
  USER_ID_SEQ BIGINT(11)   NOT NULL AUTO_INCREMENT,
  USER_NAME   VARCHAR(20)  NOT NULL,
  PASSWORD    VARCHAR(20)  NOT NULL,
#   CREATED_BY  VARCHAR(30)  NOT NULL DEFAULT 'ADMIN',
#   DTM_CREATED TIMESTAMP    NOT NULL DEFAULT '0000-00-00 00:00:00',
#   MOD_BY      VARCHAR(30)  NULL DEFAULT NULL,
#   DTM_MOD     TIMESTAMP    NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (USER_ID_SEQ)
)ENGINE =INNODB;

CREATE TABLE BUDGETS (
  BUDG_ID_SEQ BIGINT(11)   NOT NULL AUTO_INCREMENT,
  USER_ID_SEQ BIGINT(11)   NOT NULL,
  DESCR       VARCHAR(128) NOT NULL,
#   CREATED_BY  VARCHAR(30)  NOT NULL DEFAULT 'ADMIN',
#   DTM_CREATED TIMESTAMP    NOT NULL DEFAULT '0000-00-00 00:00:00',
#   MOD_BY      VARCHAR(30)  NULL DEFAULT NULL,
#   DTM_MOD     TIMESTAMP    NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (BUDG_ID_SEQ),
  INDEX BUDG_USER_FK (USER_ID_SEQ)
)ENGINE =INNODB;

ALTER TABLE BUDGETS ADD CONSTRAINT BUDG_USER_FK FOREIGN KEY (USER_ID_SEQ) REFERENCES USERS (USER_ID_SEQ);

CREATE TABLE EXPENSES (
  EXPS_ID_SEQ BIGINT(11)      NOT NULL AUTO_INCREMENT,
  BUDG_ID_SEQ BIGINT(11)      NOT NULL,
  DESCR       VARCHAR(128)    NOT NULL,
  AMOUNT      DECIMAL(11, 2)  NULL,
  DUE_DATE    TIMESTAMP       NULL,
#   CREATED_BY  VARCHAR(30)     NOT NULL DEFAULT 'ADMIN',
#   DTM_CREATED TIMESTAMP       NOT NULL DEFAULT '0000-00-00 00:00:00',
#   MOD_BY      VARCHAR(30)     NULL DEFAULT NULL,
#   DTM_MOD     TIMESTAMP       NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (EXPS_ID_SEQ),
  INDEX EXPS_BUDG_FK (BUDG_ID_SEQ)
)ENGINE =INNODB;

ALTER TABLE EXPENSES ADD CONSTRAINT EXPS_BUDG_FK FOREIGN KEY (BUDG_ID_SEQ) REFERENCES BUDGETS (BUDG_ID_SEQ);

CREATE TABLE DEBTS (
  DEBT_ID_SEQ BIGINT(11)      NOT NULL AUTO_INCREMENT,
  BUDG_ID_SEQ BIGINT(11)      NOT NULL,
  DESCR       VARCHAR(128)    NOT NULL,
  PAY_AMOUNT  DECIMAL(11, 2)  NULL,
  DUE_DATE    TIMESTAMP       NULL,
  RATE        DECIMAL(11, 2)  NULL,
  TOTAL_LEFT  DECIMAL(11, 2)  NULL,
#   CREATED_BY  VARCHAR(30)     NOT NULL DEFAULT 'ADMIN',
#   DTM_CREATED TIMESTAMP       NOT NULL DEFAULT '0000-00-00 00:00:00',
#   MOD_BY      VARCHAR(30)     NULL DEFAULT NULL,
#   DTM_MOD     TIMESTAMP       NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (DEBT_ID_SEQ),
  INDEX DEBT_BUDG_FK (BUDG_ID_SEQ)
)ENGINE =INNODB;

ALTER TABLE DEBTS ADD CONSTRAINT DEBT_BUDG_FK FOREIGN KEY (BUDG_ID_SEQ) REFERENCES BUDGETS (BUDG_ID_SEQ);



